# Generated by Django 3.0.6 on 2020-06-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='socre',
            field=models.IntegerField(default=0),
        ),
    ]
