# Generated by Django 3.0.6 on 2020-06-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdj', '0002_score_socre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['score']},
        ),
        migrations.RenameField(
            model_name='score',
            old_name='socre',
            new_name='score',
        ),
        migrations.AlterModelTable(
            name='score',
            table='t_score',
        ),
    ]
